# Generated by Django 2.1.4 on 2018-12-14 02:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreReceptor', models.CharField(max_length=30, verbose_name='Nombre del receptor')),
                ('id_ascensor', models.CharField(max_length=10, unique=True, verbose_name='ID ascensor')),
                ('piezas', models.CharField(max_length=30, verbose_name='Piezas cambiadas')),
                ('reparaciones', models.CharField(max_length=50, verbose_name='Reparaciones efectuadas')),
                ('fallas', models.CharField(max_length=50, verbose_name='Fallas detectadas')),
                ('hora_inicio', models.DateTimeField(auto_now_add=True)),
                ('hora_termino', models.DateTimeField(auto_now=True)),
                ('modelo_asc', models.CharField(max_length=50, verbose_name='Modelo de ascensor')),
                ('email', models.EmailField(max_length=30)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Cliente')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
